### ISSUE TITLE
#css  精灵图一种方便的实现，

### ISSUE THREAD

**Issue by Joshua-leyer** [Joshua-leyer/HCJ_note#5]
keyword : background 定位

```css

// sprite 
.sprite {
    background: url(./assets/index.png) no-repeat 0 0;
    background-size: 28.8462rem;
    display: inline-block;
    &.sprite-news {
        width: 1.7692rem;
        height: 1.5385rem;
        background-position: 63.546% 15.517%;
    }
    // www.spritecow.com
    &.sprite-story {
        
    }
}
```
